name: Create new Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'composer.json'
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 3
      matrix:
        php-versions: [ 8.0, 8.1, 8.2 ]

    name: Test on PHP ${{ matrix.php-versions }}
    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: intl, mbstring

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: php-${{ matrix.php-versions }}-composer-${{ hashFiles('composer.lock') }}

      - name: Install composer dependencies
        run: composer install

      - name: Run PHPunit
        run: composer run test-cover-clover

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./Tests/Coverage.xml

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - name: Create Changelog and bump release version
        uses: labor-digital/conventional-release-action@master
        with:
          github-token: ${{ secrets.github_token }}
